### ISSUE TITLE
How to customize react-crm to call REST API 

### ISSUE THREAD

**Issue by prasanta303** [harryho/react-crm#12]
I have my REST APIs ready. These customized REST API services do the CRUD operations. I want to call these APIs from **react-crm** app. 
So, my objective is **react-crm** app accesses customized REST API and show data accordingly in the UI.
Information or data should be populated/manipulated through custom REST API and **react-crm** app accesses those customized REST API to reflect in UI.
I have cloned **master branch of react-crm** from the GitHub.
Please suggest how can I customize **react-crm** to achieve the above needs.

**Comment by harryho** [comment]
Hi @prasanta303, 

This project is supposed for the developers who know react and the relevant libraries, like Thunk, Redux, etc. If you are familiar with those tech stacks, it won't be too difficult to change them. The first version of this application was built with back-end api ( Json-Server), but I replaced it with a fake Json file after version 2 because it is easy for me to maintain for the long run. You can take a look the branch json-server if you want, but it is not longer maintained. I'm closing this issue now.
